title: Compuficial
description: Welcome to my corner of the internet.
url: "https://compuficial.github.io"
baseurl: ""

permalink: /blog/:year/:month/:day/:title/

collections:
  notes:
    output: true
    permalink: /notes/:name/
    sort_by: date

header_pages:
  - blog.md
  - notes.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
